# Generated by Django 3.0.3 on 2020-04-01 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20200401_1317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_auto_20200401_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('zip_code', models.IntegerField(verbose_name='zip_code')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('price_level', models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], verbose_name='price_level')),
                ('image', models.ImageField(blank=True, upload_to='restaurant_image')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='opening_hours')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.Categories')),
                ('reviews', models.ManyToManyField(blank=True, to='reviews.Reviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
