# Generated by Django 3.0.3 on 2020-04-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200401_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='reviews',
        ),
    ]
