# Generated by Django 3.0.3 on 2020-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurants_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='category',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='price_level',
            field=models.CharField(choices=[('LOW', '$'), ('MEDIUM', '$$'), ('HIGH', '$$$')], max_length=50, verbose_name='price_level'),
        ),
    ]
