# Generated by Django 3.0.3 on 2020-04-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category'),
        ('restaurants', '0004_auto_20200402_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='categories.Category'),
            preserve_default=False,
        ),
    ]
