version:  '3'

services:
  backend:
    image: backend
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'sh /scripts/dev.sh'
    # outcomment previous command and comment in following command if you want to use ssh connection between PyCharm and Docker (Brilla needs it)
    # command: '/usr/sbin/sshd -D'

    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/dev.env

volumes:
  media-files:
  static-files:
  postgres: