name: backend
dependencies:
  - python=3.7.6
  - psycopg2
  - pip:
      - django==3.0.3
      - djangorestframework==3.11.0
      - djangorestframework-simplejwt==4.4.0
      - django-filter==2.2.0
      - coreapi==2.3.3
      - mixer==6.1.3
      - gunicorn
      - flake8
      - django-rest-passwordreset
      - Markdown==3.2.1
      - pillow==7.0.0
      - django-cors-headers==3.2.1