# Generated by Django 3.0.3 on 2020-03-31 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0002_auto_20200331_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='token',
            field=models.CharField(blank=True, help_text='6 digit string token', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='token_type',
            field=models.CharField(blank=True, choices=[('PASSWORD', 'PASSWORD'), ('SIGNUP', 'SIGNUP')], help_text='"SIGNUP" for new users / "PASSWORD" for password resets', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='user',
            field=models.ForeignKey(blank=True, help_text="User's email address", on_delete=django.db.models.deletion.CASCADE, related_name='usertoken', to=settings.AUTH_USER_MODEL),
        ),
    ]
