# Generated by Django 3.0.3 on 2020-04-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200401_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
