# Generated by Django 3.0.3 on 2020-04-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='modified_date',
            new_name='date_modified',
        ),
    ]
