# Generated by Django 3.0.3 on 2020-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comments_reviews'),
        ('reviews', '0002_auto_20200401_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='comments.Comments'),
        ),
    ]
