# Generated by Django 3.0.3 on 2020-04-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviews_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='comments',
        ),
    ]
