# Generated by Django 3.0.3 on 2020-04-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200401_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reviews',
        ),
    ]
