# Generated by Django 3.0.3 on 2020-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comments_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text_content',
            field=models.CharField(max_length=255, verbose_name='comment_text_content'),
        ),
    ]
