# Generated by Django 3.0.3 on 2020-04-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_reviews_comments'),
        ('comments', '0004_auto_20200401_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='review',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Reviews'),
            preserve_default=False,
        ),
    ]
